version: '2'

services:
  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/nginx/certs:/etc/nginx/certs
      - /var/docker/nginx/vhost:/etc/nginx/vhost.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/nginx/acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: <<EMAIL>>

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - "8080"     
    environment:
      VIRTUAL_HOST: <<HOST>>
      LETSENCRYPT_HOST: <<HOST>>
      WORDPRESS_DB_HOST: <<DB>>:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: <<USER_DB>>
      WORDPRESS_DB_PASSWORD: <<PWD_DB>>
    volumes:
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini

  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    depends_on:
      - db
      - wp      

volumes:
    db_data: