version: '2'

services:
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - app-network
       
  # phpmyadmin:
  #     image: phpmyadmin/phpmyadmin
  #     depends_on:
  #       - db
  #     restart: always
  #     ports:
  #       - "3333:3306"
  #     environment:
  #       PMA_HOST: db
  #       MYSQL_ROOT_PASSWORT: somewordpress  
  #     volumes:
  #       - ./wordpress.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini       
   
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: always
    ports: 
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network    

  certbot:
      depends_on:
        - webserver
      image: certbot/certbot
      container_name: certbot
      volumes:
        - certbot-etc:/etc/letsencrypt
        - wordpress:/var/www/html
      command: certonly --webroot --webroot-path=/var/www/html --email nestor.junior@gmail.com --agree-tos --no-eff-email --force-renewal -d abpdf.tk -d www.abpdf.tk

volumes:
  certbot-etc:
  wordpress:
  db_data:

networks:
  app-network:
    driver: bridge