version: '2'

services:
  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/nginx/certs:/etc/nginx/certs
      - /var/docker/nginx/vhost:/etc/nginx/vhost.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/nginx/acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: nestor.junior@gmail.com

  # wordpress:
  #   image: wordpress:latest
  #   container_name: wordpress
  #   restart: unless-stopped
  #   expose:
  #     - "8080"     
  #   environment:
  #     VIRTUAL_HOST: abpdf.tk
  #     LETSENCRYPT_HOST: abpdf.tk    
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: wordpress
  #   volumes:
  #     - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini      

  # hello-world:
  #   container_name: hello-world
  #   image: kornkitti/express-hello-world
  #   expose:
  #     - "8080"
  #   environment:
  #     VIRTUAL_HOST: abpdf.tk
  #     LETSENCRYPT_HOST: abpdf.tk